./make_coral.sh host-uboot-tools-dirclean
./make_coral.sh uboot-tools-dirclean
./make_coral.sh uboot-dirclean
./make_coral.sh linux-dirclean
#./make_coral.sh docker-dirclean
#./make_coral.sh docker-cli-dirclean
#./make_coral.sh docker-compose-dirclean
#./make_coral.sh docker-engine-dirclean
#./make_coral.sh docker-proxy-dirclean
